export const APP_ROUTES = {
  ACCUEIL: "/",
  HEADER: "header",
  //RECIPE: "/",

  DISPLAY: "/display",
  SIGN_IN: "/sign-in",
  SIGN_UP: "/sign-app",
  RECIPE: "/recipe",
  CARD: "/card",
  ALLCARD: "/allcard",
  FILTER: "/filter",
  SEARCH: "/search",
  FOOTER: "/footer",
  UPDATE: "/update",
  PROFIL: "/profil",
  DASHBOARD: "/dashboard",
  NAV: "/nav",
  INGREDIENT: "/ingredient",
  EDITRECIPE: "/editrecipe",
  EDITSTEP: "/editstep",
  EDITINGREDIENT: "/editingredient",
  APROPOS: "/apropos",
  DASHBOARDADMIN: "/dashboardAdmin",
  CONTACT: "/contact",
  EDITCOMMENT: "/editcomment",
  EDITFAVORIS: "editfavoris",
  FAVORITE: "/favorite",
  MESSAGE: "/message",
  URL: "http://mounirahammoudi.sites.3wa.io:9001/uploads/",

};
